### ISSUE TITLE
Pin diagrams if you have them

### ISSUE THREAD

**Issue by jsatishb** [sid8840/RV400-immobalizer#1]
Hi,
It will be helpful if you could do some work and publish the pin diagrams.  
I dont think that the immobiliser is responsible to convert 83~72v to 12V and 5V as you have indicated.

You should also look at the ECU unit / which collects data from the controller and the GPS antenna to broadcast the same to MyRevolt app.

**Comment by sid8840** [comment]
The immobilizer converts 80v to 12v for Start stop button led and 5v for RF receiver.
to extract data from ECU unit is my next task so that swipe to start button can be mimicked.

p.s.
I will be out for two weeks.

**Comment by sid8840** [comment]
> Hi, It will be helpful if you could do some work and publish the pin diagrams. I dont think that the immobiliser is responsible to convert 83~72v to 12V and 5V as you have indicated.
> 
> You should also look at the ECU unit / which collects data from the controller and the GPS antenna to broadcast the same to MyRevolt app.

![Pin out](https://github.com/sid8840/RV400-immobalizer/assets/83544106/164188c6-65c2-4ace-9646-815fceeec0fd)

![cv29dygvnqda1](https://github.com/sid8840/RV400-immobalizer/assets/83544106/7acd64cd-f888-49ed-9163-d64263a5329a)
